### ISSUE TITLE
Powershell gallery

### ISSUE THREAD

**Issue by gregpakes** [lordmilko/PrtgAPI.CustomSensors#1]
I would like to use this in my own repository of custom sensors.  I'm looking at how to include it with my repo.  Do you have any plans to put it in the Powershell Gallery?

I think this would help another issue I am having with Powershell Remoting.  I am writing a sensor which uses remoting, but it does not seem trivial to get the module to work through remoting.  How have you solved this issue previously?

**Comment by lordmilko** [comment]
Hi gregpakes,

I am currently working on getting the module working in NuGet, so you will eventually be able to install the module by running "Install-Package PrtgAPI.CustomSensors". I am currently in the final stages of testing things before I pull the trigger on this.

You make a good point about doing PowerShell remoting. Eventually, you should just be able to do a check that the package is installed and if not install it from NuGet. I did a bit of research into importing modules from your local session into your remote session, and it does seem to be a common problem. people find themselves faced with.

When I tested importing the module into my remote session, while each function worked fine individually, PowerShell threw a hissy fit when I tried to use functions nested inside script blocks.

I'd be interested in knowing what your perspective is on the solution of having your sensors install the missing module on the servers they target. This will certainly be an issue I will have to resolve as I start using this module for more of my clients sensors!

I am intrigued to know why the functions don't work consistently when imported via [recommended strategies](https://adsecurity.org/?p=303), and will continue to investigate

Regards,
lordmilko

**Comment by gregpakes** [comment]
@lordmilko 

I think your remoting solution is acceptable.  I would certainly be happy using that.   When this is available I'll start using your library.

**Comment by lordmilko** [comment]
@gregpakes 

PrtgAPI.CustomSensors is now on PSGallery. If you are interested in writing portable scripts that will be used on a variety of systems, the following code works well

```powershell
Invoke-Command -Computername $computerName {

    if(!(Get-Module -ListAvailable PrtgAPI.CustomSensors))
    {
        Install-Package PrtgAPI.CustomSensors -ForceBootstrap -Force | Out-Null
    }

    Prtg {
        Result {
            Channel "My channel"
            Value 3
        }
    }
}
```

`-ForceBootstrap` installs the NuGet Package Provider and `-Force` tells Install-Package to not prompt to confirm installation. Out-Null disables the output that says the module has been installed.

**Comment by gregpakes** [comment]
Thanks - I'll give it a go and let you know.
