### ISSUE TITLE
Example with multiple results

### ISSUE THREAD

**Issue by aaronaxvig** [lordmilko/PrtgAPI.CustomSensors#3]
It would be nice to have an example in either `docs/Prtg.md` or `docs/Result.md` of what it would look like to have multiple `result` nodes.

**Comment by lordmilko** [comment]
Hi @aaronaxvig,

The "syntax" of PrtgXml simply consists of functions and script blocks. As such, you can generate multiple `result` nodes by specifying a loop, writing them manually, or any other means that is valid PowerShell

```powershell
Prtg {
    Result {
        ...
    }

    Result {
        ...
    }
}
```

Regards,
lordmilko

**Comment by aaronaxvig** [comment]
Sure, I figured that out after sifting through the documentation for 5-10 minutes. I would have found the explanation and example that you provided above to be quite helpful.
